main: com.killcollectitem.App
name: KillCollectItem
version: 1.0
api-version: '1.8'
author: jpgoreczky
description: A plugin that allows players to collect loot from killed players in a GUI.

commands:
  collect:
    description: Opens the Kill Collection GUI.
    usage: /collect
    permission: killcollectitem.collect
  collectclear:
    description: Clears the player's items in the loot collection GUI.
    usage: /collectclear
    permission: killcollectitem.collect.clear
  collectsetting: 
    desciption: Allows players to configure collected items for their GUI.
    usage: /collectsetting <add/remove/list>
    permission: killcollectitem.collect.setting

permissions:
  killcollectitem.collect:
    description: Permission to use /collect command
    default: true
    children: 
      killcollectitem.collect.clear: true
      killcollectitem.collect.setting: true
  killcollectitem.collect.clear:
    description: Permission to clear the loot inventory
  killcollectitem.collect.setting:
    description: Permission to set collected items